api/urls.py
from django.urls import path
from . import views
from rest_framework import routers



urlpatterns = [
    path('', views.apiOverview, name='api'),
    path('order-list/', views.getAllOrders, name='order-list'),
    path('order-detail/<str:pk>/', views.orderDetail, name='order-detail'),
    path('order-update/<str:pk>/', views.orderUpdate, name='order-update'),
    path('order-delete/<str:pk>/', views.orderDelete, name='order-delete'),
    
    path('search/', views.getProductsOnSearch, name='search'),
    path('product-list/', views.getAllProducts, name='product-list'),
    path('popular-products/', views.getMostPopularProducts, name='popular-products'),
    path('product-infinite/', views.infinte_scroll_view.as_view(), name='product-infinite'),
    path('categories-list/', views.getAllCategories, name='cat-list')

]

inventario/urls.py
import os

from dotenv import load_dotenv
load_dotenv()

from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from api.views import getProductsOnSearch
from inventario_app.views import (Index,
    cart, order_confirmation, CreateProductView,
    AdminProductListView, detail, update, ProductDelete, Contact)

from django.contrib.auth import views as auth_views

urlpatterns = [
    path(os.getenv('SECRET_ADMIN_URL') + '/admin/', admin.site.urls),
    path('', Index, name='index'),
    path('contact/', Contact, name='contact'),
    path('api/', include('api.urls')),
    path('cart/', cart, name='cart'),
    path('email-confirmation/', order_confirmation, name='email-confirmation'),
    path('create/', CreateProductView, name='create'),
    path('admin-product-list', AdminProductListView, name='admin-product-list'),
    path('product/<id>/', detail, name='detail'),
    path('product/<id>/update/', update, name='update'),
    path('product/<int:pk>/delete/', ProductDelete.as_view(), name='delete'),
    path('accounts/login/', auth_views.LoginView.as_view()),

    path('captcha/', include('captcha.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

inventario_app/models.py
from django.db import models
from django.utils import timezone

class Product(models.Model):

    choices = (
        ('100g', 0),
        ('200g', 0),
        ('300g', 0),
    )

    name = models.CharField(max_length=50, verbose_name="nombre")
    price = models.DecimalField(max_digits = 6, decimal_places= 2, verbose_name="precio", null=True, blank=True)
    sold_by_weight = models.BooleanField(default = False, verbose_name= 'Producto Vendido x Peso')
    price_100g = models.DecimalField(max_digits = 6, decimal_places= 2, verbose_name="precio por 100g", null=True, blank=True)
    price_200g = models.DecimalField(max_digits = 6, decimal_places= 2, verbose_name="precio por 200g", null=True, blank=True)
    price_300g = models.DecimalField(max_digits = 6, decimal_places= 2, verbose_name="precio por 300g", null=True, blank=True)
    description = models.TextField(max_length=400, verbose_name="descripcion", null=True, blank=True)
    timestamp = models.DateTimeField(default=timezone.now,blank=True, null=True)
    image = models.ImageField(default='chocolate.jpg',blank=True, null=True, verbose_name='imagen')
    category = models.ManyToManyField("Category", verbose_name='categoria', blank=True)
    views = models.IntegerField(default = 0, null=True, blank=True)
    is_bundle = models.BooleanField(default = False, verbose_name='Es Promocion')
    in_stock = models.BooleanField(default = True, verbose_name='En Stock')

    class Meta:
        verbose_name = "Producto"
        verbose_name_plural = "Productos"

    def save(self, *args, **kwargs):
        return super(Product, self).save(*args, **kwargs)

    def __str__(self):
        return self.name

class Category(models.Model):
    name = models.CharField(max_length=50, verbose_name='Categorias')

    class Meta:
        verbose_name = "Categoria"
        verbose_name_plural = "Categorias"

    def __str__(self):
        return self.name

class OrderItem(models.Model):
    product = models.ForeignKey('Product', on_delete=models.SET_NULL, null=True, related_name='product')
    product_name = models.CharField(max_length=50, null=True, blank=True)
    product_price = models.DecimalField(max_digits = 6, decimal_places= 2, null=True, blank=True)
    sold_by_weight_info = models.CharField(max_length=50, null=True, blank=True)
    quantity = models.IntegerField(default=1, null=True, blank=True)
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = "Order Item"
        verbose_name_plural = "Order Items"

    @property
    def add(self):
        self.quantity += 1
    @property
    def take(self):
        self.quantity += 1

class Order(models.Model):
    items = models.ManyToManyField("OrderItem", related_name='products')
    date_ordered = models.DateTimeField(auto_now_add=True)
    complete = models.BooleanField(default=False)
    customer_name = models.CharField(max_length=100, blank=True)
    customer_email = models.CharField(max_length=100, blank=True)
    customer_phone_number = models.CharField(max_length=100, blank=True)
    customer_location = models.CharField(max_length=100, blank=True)
    customer_address = models.CharField(max_length=100, blank=True)
    active = models.BooleanField(default=True)
    gift = models.BooleanField(default=False)

    class Meta:
        verbose_name = "Orden"
        verbose_name_plural = "Ordenes"

    def __str__(self):
        return str(self.id)

    @property
    def get_cart_total(self):
        orderitems = self.items.all()
        for i in orderitems:
            print(i.product_name, type(i.product_price))
        total = sum([item.product_price * item.quantity for item in orderitems])
        return total

    @property
    def get_cart_items(self):
        orderitems = self.items.all()
        total = sum([item.quantity for item in orderitems])
        return total

inventario_app/forms.py
from django import forms
from django.forms import ModelForm
from inventario_app.models import Product
from django.urls import reverse
from captcha.fields import CaptchaField

class CreateProductForm(ModelForm):

    class Meta:
        model = Product
        fields = ['name','price', 'sold_by_weight','price_100g','price_200g','price_300g','description','category','image', 'is_bundle', 'in_stock']
        widgets = {
            'category': forms.CheckboxSelectMultiple(),
        }
        
choices = (
    ('1', 'Rosario'),
    ('2', 'Funes'),
    ('3', 'Roldán')
)

class EmailConfirmationForm(forms.Form):
    name = forms.CharField(max_length=100, required=True, label='Nombre')
    surname = forms.CharField(max_length=100, required=True, label='Apellido')
    phone_number = forms.CharField(max_length=20, help_text='Ej. 3415778972.', label='Teléfono')
    location = forms.ChoiceField(choices = choices, label='Localidad')
    customer_address = forms.CharField(max_length=100, label='Domicilio')
    email = forms.EmailField(required=False, help_text='Agregue email si desea recibir orden por correo electrónico.')
    gift = forms.BooleanField(label='Para Regalar!', required=False)
    order_items = forms.JSONField(widget=forms.HiddenInput()) 
    captcha = CaptchaField()

    def clean_location(self):
        value = self.cleaned_data.get('location')
        return dict(self.fields['location'].choices)[value]
    

inventario_app/views.py
from django.conf import settings
import json

from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import redirect, render, get_object_or_404
from django.urls import reverse, reverse_lazy
from django.db.models import Q
from django.contrib import messages

from django.core.mail import send_mail
from django.utils.encoding import force_bytes, force_text
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from .tokens import order_tokenizer
from django.template.loader import get_template
from django.core.mail import EmailMessage

from .models import Product, OrderItem, Order
from .forms import CreateProductForm, EmailConfirmationForm
from django.views.generic import FormView, CreateView, DetailView, View, DeleteView

from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin

from django.views.decorators.csrf import csrf_exempt

from api.serializers import ProductSerializer


def Index(request):
    return render(request, 'inventario_app/index.html')

def Contact(request):
    return render(request, 'inventario_app/contact.html')

def serve_search_template(request):
    query = request.GET.get('q')
    return render(request, "inventario_app/search_results.html", context={"q":query})

# Admin UI Views

@login_required
def CreateProductView(request):
    form = CreateProductForm()
    if request.method == "POST":
        form = CreateProductForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            messages.info(request, 'Se ha agregado un nuevo producto a la base de datos')
            return HttpResponseRedirect(reverse('index'))
    return render(request, "inventario_app/admin_create_product.html", context = {"form": form})

class ProductDelete(LoginRequiredMixin, SuccessMessageMixin, DeleteView):
    template_name = 'inventario_app/admin_delete_confirmation.html'
    model = Product
    success_url = reverse_lazy('index')

@login_required
def AdminProductListView(request):
    products = Product.objects.all().order_by('name')
    return render(request, 'inventario_app/admin_product_list.html', {'products': products})

def detail(request, id):    
    qs = get_object_or_404(Product, id=id)
    product_data = {
        "id": qs.id,
        "name": qs.name,
        "price": qs.price,
        "sold_by_weight": qs.sold_by_weight,
        "price_100g": qs.price_100g,
        "price_200g": qs.price_200g,
        "price_300g": qs.price_300g,
    }
    mydata = qs.id
    context = {'product': qs, 'product_data': product_data}
    if qs.sold_by_weight:
        context['sold_by_weight'] = [("100g",qs.price_100g),("200g",qs.price_200g),("300g",qs.price_300g)]
    return render(request, 'inventario_app/detail_view.html', context)

@login_required
def update(request, id):
    qs = get_object_or_404(Product, id=id)
    form = CreateProductForm(instance = qs)
    if request.method == "POST":
        form = CreateProductForm(request.POST, request.FILES, instance = qs)
        if form.is_valid():
            if form.cleaned_data['sold_by_weight']:
                form.cleaned_data['price'] = None
            form.save()
            return HttpResponseRedirect(reverse('index'))
    return render(request, "inventario_app/update_product.html", context = {"form": form, "product":qs})

# def SearchProducts(request):
#     queryset = Product.objects.all()
#     query = request.GET.get('q')
#     if query:
#         queryset = queryset.filter(
#             Q(name__icontains=query) |
#             Q(description__icontains=query) |
#             Q(category__name__icontains=query)
#         ).distinct()
#     context = {
#         'products': queryset
#     }
#     return render(request, 'inventario_app/search_results.html', context)

def removeFromCart(request, id):
    item = get_object_or_404(Product, id = id)
    key = 'cart_id'
    if key in request.session:
        session_id = request.session[key]
        order = get_object_or_404(Order, id = session_id)
        if order.items.filter(product__id = item.id).exists():
            orderitem_object = order.items.filter(product__id = item.id)[0]
            orderitem_object.quantity -= 1
            orderitem_object.save()
    context = {'order':order}
    return HttpResponseRedirect(reverse('cart'))

def cart(request):
    return render(request, 'inventario_app/cart.html')

@csrf_exempt
def order_confirmation(request):
    form = EmailConfirmationForm()
    if request.method == 'POST':
        form = EmailConfirmationForm(request.POST)
        if form.is_valid():
            if form.cleaned_data["order_items"]:
                order_items = []
                for element in form.cleaned_data["order_items"]:
                    product = Product.objects.get(id = element["id"])
                    if element["sold_by_weight"] == False:
                        order_item = OrderItem(
                            product = product,
                            product_name=element["product_name"],
                            quantity=element["quantity"],
                            product_price = product.price)
                        order_item.save()
                        order_items.append(order_item) 
                    else:
                        weight_price = element["sold_by_weight"].split()[1]
                        order_item = OrderItem(
                            product_name=element["product_name"],
                            product=product,
                            quantity=element["quantity"],
                            sold_by_weight_info=weight_price)
                        if weight_price == '100g':
                            order_item.product_price = product.price_100g
                        elif weight_price == '200g':
                            order_item.product_price = product.price_200g
                        elif weight_price == '300g':
                            order_item.product_price = product.price_300g
                        order_item.save()
                        order_items.append(order_item)
                customer_name = f"{form.cleaned_data['name']} {form.cleaned_data['surname']}"
                order = Order(
                    customer_name=customer_name,
                    customer_email=form.cleaned_data["email"],
                    customer_phone_number=form.cleaned_data["phone_number"],
                    customer_location=form.cleaned_data["location"],
                    customer_address=form.cleaned_data["customer_address"],
                    gift=form.cleaned_data['gift'])
                order_items_total = sum(item.product_price * item.quantity for item in order_items)
                if order_items_total < 1000:
                    # fields valid but order less than minimum
                        for item in order_items:
                            item.delete()
                        messages.warning(request, 'La compra mínima es de $1000 más el envío.')
                        return redirect('/?q=failed')
                order.save()
                order.items.set(order_items)
                order.save()
                message = get_template('inventario_app/email_confirmation_shop.html').render({
                    'order': order,
                })
                mail = EmailMessage(
                    'Dulceria Funes',
                    message,
                    settings.EMAIL_HOST_USER,
                    [settings.EMAIL_HOST_USER],
                    )
                mail.content_subtype = 'html'
                mail.send()
                if form.cleaned_data['email']:         
                    customer_email = form.cleaned_data['email']
                    message = get_template('inventario_app/email_confirmation_customer.html').render({
                        'order': order,
                    })
                    mail = EmailMessage(
                        'Dulceria Funes',
                        message,
                        settings.EMAIL_HOST_USER,
                        [customer_email],
                        )
                    mail.content_subtype = 'html'
                    mail.send()
                request.session['order_completed'] = True
                request.session.set_expiry(1)
                order.save()
                messages.success(request, 'Orden enviada. Nos contactaremos con usted para ultimar detalles del pedido.')
                return redirect('/?q=success')
            else:          
                # reCAPTCHA valid but order empty 
                # creates a new order on the client side from scratch
                request.session['order_failed'] = True
                request.session.set_expiry(1)
                messages.warning(request, 'No puede enviar una orden vacia.')
                return redirect('/?q=failed')
        else:
            # at least one of the fields is not valid (empty order items or failed reCAPTCHA)
            messages.warning(request, 'reCAPTCHA incorrecto u orden vacía, inténtelo de nuevo.')
            return redirect('/?q=failed')
    context = {"form": form}
    return render(request, 'inventario_app/email_confirmation.html', context)

inventario_app/templates/inventario_app/admin_create_product.html
{% extends 'inventario_app/base.html' %}
{% load crispy_forms_tags %}


{% block body %}
<div class="create-product row justify-content-md-center">
    <div class="">
    <h2>Agregar nuevo producto</h2> 
    <form action="{% url 'create' %}" method="POST" name='create-product' enctype="multipart/form-data">
        {% csrf_token %}
        {{ form | crispy }}
    <br>  
    <button class="btn btn-success" type='submit'>Crear</button>
    </form>
    </div>
</div>

<script>
    (function() {
        const list_of_fields = [document.querySelector('#id_price_100g'),                
                                document.querySelector('#id_price_200g'),
                                document.querySelector('#id_price_300g')]
        list_of_fields.forEach((field) => {
                field.disabled = true
        });
        document.querySelector('#id_sold_by_weight').addEventListener('click', () =>{
           if(!document.querySelector('#id_price').disabled){
            document.querySelector('#id_price').disabled = true
            list_of_fields.forEach((field) => {
                field.disabled = false
        });
           }else{
            document.querySelector('#id_price').disabled = false
            list_of_fields.forEach((field) => {
                field.disabled = true
            });
           };
        });
    })();
</script>
{% endblock %}

inventario_app/templates/inventario_app/admin_delete_confirmation.html
{% extends 'inventario_app/base.html' %}
{% load crispy_forms_tags %}


{% block body %}

<form method="post">{% csrf_token %}
    <p>Estas seguro que quieres borrar "{{ object }}" de la base de datos?</p>
    <input class='btn btn-success' type="submit" value="Confirmar">
    <a class='btn btn-danger' href="{% url 'admin-product-list' %}"> Cancelar</a>
</form>

{% endblock body %}

inventario_app/templates/inventario_app/admin_product_list.html
{% extends 'inventario_app/base.html' %}
{% load crispy_forms_tags %}


{% block body %}
<div class="row justify-content-md-center"><br>
        <h2>Lista de Productos</h2> 
    </div>
    <div class="row justify-content-md-center">
        <div class="col">
            <ul>
                {% for product in products %}
                <li><a href="{% url 'update' product.id %}">{{product.name}}</a>
                <a class="fas fa-trash-alt" href="{% url 'delete' product.id %}"></a></li>
                {% endfor%}
            </ul>
        </div>
    </div>
</div>
   
    

{% endblock %}

inventario_app/templates/inventario_app/cart.html
{% extends 'inventario_app/base.html' %}
{% load static %}
{% block body %}
		<div id="order-row" class="row">
			<div class="col-lg-8">
				<div id="order-div" class="box-element p-4">
					<a id='inicio' class="btn btn-outline-dark" href="{% url 'index' %}">&#x2190; Inicio</a>
					<a class='continue-button btn btn-outline-dark float-right' href="{% url 'email-confirmation' %}">Continuar &#x2192</a>
					<hr>
					<h3 style="display:inline-block;">Resumen de orden</h3><span style="font-size:medium; margin-left: 1px"><p>(La compra mínima es de $1000 más el envío)</p></span>
					<hr>
					<div id="items-div">
					</div>
						<div id="order-items">
							<ol>
							</ol>
						</div>
						<div id='total'>
						</div>
					</div>
			</div>
		</div>

<script type='module' src='{% static "js/cart.js"%}'> </script>

<style>
	.disabled {
		cursor: not-allowed;
		opacity: 0.65;
		filter: alpha(opacity=65);
		box-shadow: none;
	}
</style>
{% endblock %}

inventario_app/templates/inventario_app/checkout (not used).html
{% extends 'store/main.html' %}
{% load static %}

{% block body %}
	<h1>Cart</h1>
	<div class="row">
		<div class="col-lg-12">
			<div class="box-element">
				<a  class="btn btn-outline-dark" href="{% url 'index' %}">&#x2190; Continuar la compra</a>
				<br>
				<br>
				<table class="table">
					<tr>
						<th><h5>Items: <strong>{{order.get_cart_items}}</strong></h5></th>
						<th><h5>Total:<strong> ${{order.get_cart_total|floatformat:2}}</strong></h5></th>
						<th>
							<a  style="float:right; margin:5px;" class="btn btn-success" href="{% url 'checkout' %}">Checkout</a>
						</th>
					</tr>
				</table>
			</div>

			<br>
			<div class="box-element">
				<div class="cart-row">
					<div style="flex:2"></div>
					<div style="flex:2"><strong>Item</strong></div>
					<div style="flex:1"><strong>Price</strong></div>
					<div style="flex:1"><strong>Quantity</strong></div>
					<div style="flex:1"><strong>Total</strong></div>
				</div>
				{% for item in items %}
				<div class="cart-row">
					<div style="flex:2"><img class="row-image" src="{{item.product.imageURL}}"></div>
					<div style="flex:2"><p>{{item.product.name}}</p></div>
					<div style="flex:1"><p>${{item.product.price|floatformat:2}}</p></div>
					<div style="flex:1">
						<p class="quantity">{{item.quantity}}</p>
						<div class="quantity">
							<img data-product="{{item.product.id}}" data-action="add" class="chg-quantity update-cart" src="{% static  'images/arrow-up.png' %}">
					
							<img data-product="{{item.product.id}}" data-action="remove" class="chg-quantity update-cart" src="{% static  'images/arrow-down.png' %}">
						</div>
					</div>
					<div style="flex:1"><p>${{item.get_total|floatformat:2}}</p></div>
				</div>
				{% endfor %}
			</div>
		</div>
	</div>
	
{% endblock body %}

inventario_app/templates/inventario_app/contact.html
{% extends 'inventario_app/base.html' %}
{% load static %}

{% block body %}
<div style="height: 80vh; margin-top: 15vh;" class="row justify-content-md-center">
    <div class="col-md-4">
        <div class="contact-details">
          <p style='text-align: center; font-size: 20px;'>&#x1F389;&#x200D; Gracias por confiar en nosotros. &#x1F389;&#x200D;</p>
          <p style='text-align: center;'>Para consultas no dude en contactarnos:</p>

          <p style='text-align: center;'>Email: <a href="">funesdulceria@gmail.com</p>
          <ul style='text-align: center;' class="social-menu">
            <li class="list-inline-item pr-5"><a href="https://www.instagram.com/funes.dulceria/"><i style="font-size: 48px; color: grey; text-align: center;" class="fab fa-instagram"></i></a></li>
            <li class="list-inline-item pr-5"><a href="https://api.whatsapp.com/send/?phone=%2B5493416659897&text&app_absent=0"><i style="font-size: 48px; color: grey; text-align: center;" class="fab fa-whatsapp"></i></a></li>
          </ul>
        </div>
    </div>
</div>

{% endblock body %}

inventario_app/templates/inventario_app/create_product.html
{% extends 'inventario_app/base.html' %}
{% load crispy_forms_tags %}


{% block body %}
<div class="row justify-content-md-center">
    <div class="">
    <h2>Agregar nuevo producto</h2> 
    <form action="{% url 'create' %}" method="POST" name='create-product' enctype="multipart/form-data">
        {% csrf_token %}
        {{ form | crispy }}
    <br>  
    <button class="btn btn-success" type='submit'>Crear</button>
    </form>
</div>
   
    

{% endblock %}

inventario_app/templates/inventario_app/email_confirmation_customer.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Confirmacion de Email</title>
</head>
<body>
    <h1>Bienvenidos a Funes Dulceria</h1>
    <p>Usted ha realizado la siguiente compra</p>
    <table id='email-table'>
        <thead>
          <tr>
            <th id='email-table'>#</th>
            <th id='email-table'>Producto</th>
            <th id='email-table'>Cantidad</th>
            <th id='email-table'>Precio x unidad</th>
          </tr>
        </thead>
        <tbody>
            {% for item in order.items.all %}
          <tr>
            <th id='email-table'>{{ forloop.counter }}</th>
            <td id='email-table'>{{ item.product_name }}</td>
            <td id='email-table'>{{ item.quantity }}</td>
            <td id='email-table'>${{ item.product_price }}</td>
          </tr>
          {% endfor %}
          <tr>
            <th id='email-table'>#</th>
            <td id='email-table'>Envio</td>
            <td id='email-table'>#</td>
            <td id='email-table'>100</td>
          </tr>
        </tbody>
        <tbody>
        <tr>
            <td id='email-table'><h2>Cantidad: {{order.get_cart_items}} unidades</h2></td><br>
            <td id='email-table'><h2>Total: ${{order.get_cart_total|add:"100"|floatformat:2}}</h2></td>
        </tr>
        </tbody>
      </table>
      <p>Nos comunicaremos con vos por telefono para ultimar detalles</p>
    <!-- <p>Por favor clickee sobre este link para confirmar su direccion de email y completar su orden.</p>
    <h4><a href="{{ confirm_url }}">{{ confirm_url }}</h4></p>
    <p>Una vez confirmado el pedido lo contactaremos via el numero <strong>{{ customer_info.phone_number }}</strong></p> -->
</body>
</html>

inventario_app/templates/inventario_app/email_confirmation_final.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ORDEN CONFIRMADA</title>
</head>
<body>
    <h1>Orden {{ order.id }}</h1>
    <p>Cliente: {{ order.customer_name }}</p>
    <p>Telefono: {{ order.customer_phone_number }}</p>
    <p>Email: {{ order.customer_email }}</p>
    {% if order.gift %} <p><strong>Para Regalar</strong></p>{% endif %}
    
    <table class="table table-striped">
        <thead class="thead-dark">
          <tr>
            <th scope="col">#</th>
            <th scope="col">Producto</th>
            <th scope="col">Cantidad</th>
            <th scope="col">Precio x unidad</th>
          </tr>
        </thead>
        <tbody>
            {% for item in order.items.all %}
          <tr>
            <th scope="row">{{ forloop.counter }}</th>
            <td>{{ item.product.name }}</td>
            <td>{{ item.quantity }}</td>
            <td>{{ item.product.price }}</td>
          </tr>
          {% endfor %}
        </tbody>
        <tbody>
        <tr>
            <td ><h2>Cantidad: {{order.get_cart_items}} unidades</h2></td><br>
            <td ><h2>Total: ${{order.get_cart_total|floatformat:2}}</h2></td>
        </tr>
        </tbody>
      </table>

</body>
</html>

inventario_app/templates/inventario_app/email_confirmation_link.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Confirmacion de Email</title>
</head>
<body>
    <h1>Bienvenidos a Funes Dulceria</h1>
    <p>Usted ha realizado la siguiente compra</p>
    <table class="table table-striped">
        <thead class="thead-dark">
          <tr>
            <th scope="col">#</th>
            <th scope="col">Producto</th>
            <th scope="col">Cantidad</th>
            <th scope="col">Precio x unidad</th>
          </tr>
        </thead>
        <tbody>
            {% for item in order.items.all %}
          <tr>
            <th scope="row">{{ forloop.counter }}</th>
            <td>{{ item.product.name }}</td>
            <td>{{ item.quantity }}</td>
            <td>{{ item.product.price }}</td>
          </tr>
          {% endfor %}
        </tbody>
        <tbody>
        <tr>
            <td ><h2>Cantidad: {{order.get_cart_items}} unidades</h2></td><br>
            <td ><h2>Total: ${{order.get_cart_total|floatformat:2}}</h2></td>
        </tr>
        </tbody>
      </table>

    <p>Por favor clickee sobre este link para confirmar su direccion de email y completar su orden.</p>
    <h4><a href="{{ confirm_url }}">{{ confirm_url }}</h4></p>
    <p>Una vez confirmado el pedido lo contactaremos via el numero <strong>{{ customer_info.phone_number }}</strong></p>
</body>
</html>

inventario_app/templates/inventario_app/search_results.html
{% extends 'inventario_app/base.html' %}
{% block body%}

<h3>Resultados de la busqueda</h3>

<div class="row">
    {% for product in products %}
    <div class="col-lg-3">

        <a href="{% url 'detail' id=product.id%}"><img class="img-thumbnail" src="{{product.image.url}}"></a>        <div class="box-element product">
            <a href="{% url 'detail' id=product.id%}"><h6 style="display: inline-block"><strong>{{product.name}}</strong></h6></a>
            <hr>

            <a href="{% url 'add-to-cart' id=product.id%}"><button class="btn btn-outline-secondary add-btn update-cart">Agregar </button></a>
            
            <!-- <a class="btn btn-outline-primary btn-sm" href="{% url 'detail' id=product.id%}">Detalles</a> -->
            <h4 style="display: inline-block; float: right"><strong>${{product.price}}</strong></h4>
        </div>
        <br>
    </div>
    {% empty %} 
    <div class="col-lg-4">
    <p>lo sentimos mucho, no se ha encontrado nada.</p>
    </div>
    {% endfor %}
</div>


{% endblock %}